In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
import matplotlib as plt

In [3]:
dframe = pd.read_excel('jobpartitionperfanalysis.xlsx','Sheet1')
dframe

,rundate,CountStudiosWTrans,TotalTrans,Duration,JobPartition,StdDevNumTrans,TransPerStudioWTrans,DayOfMonthNumber,TotalCountStudios,TransPerTotalStudioCount,StudiosWNoTrans
0,2015-06-01,989,28496,786,WEST0112,61.630462,28.812942,1,3697,7.707871,2708
1,2015-06-01,991,24235,726,WEST0111,63.719442,24.455095,1,3710,6.532345,2719
2,2015-06-01,142,39619,634,WEST0107,1332.724143,279.007042,1,1580,25.075316,1438
3,2015-06-01,326,28038,597,EAST0101,338.004456,86.006134,1,1562,17.950064,1236
4,2015-06-01,620,23203,595,WEST0105,125.447762,37.424193,1,1749,13.266438,1129
5,2015-06-01,450,23092,593,WEST0106,133.707352,51.315555,1,1547,14.926955,1097
6,2015-06-01,794,30289,586,WEST0109,196.497427,38.147355,1,3273,9.254201,2479
7,2015-06-01,948,19252,575,EAST0110,67.806159,20.308016,1,2989,6.440950,2041
8,2015-06-01,568,18898,572,WEST0103,78.552667,33.271126,1,1483,12.743088,915
9,2015-06-01,522,24971,563,EAST0105,211.002529,47.837164,1,1874,13.324973,1352
10,2015-06-01,406,23696,539,WEST0108,251.046225,58.364532,1,2626,9.023610,2220
11,2015-06-01,721,25970,535,EAST0107,139.302143,36.019417,1,3188,8.146173,2467
12,2015-06-01,979,19972,532,WEST0110,51.938667,20.400408,1,3529,5.659394,2550
13,2015-06-01,367,24135,528,EAST0106,218.348048,65.762942,1,2301,10.488918,1934
14,2015-06-01,574,20510,522,EAST0104,92.665021,35.731707,1,1893,10.834654,1319
15,2015-06-01,565,17808,495,WEST0102,80.592640,31.518584,1,1658,10.740651,1093
16,2015-06-01,565,17867,493,WEST0104,79.245722,31.623008,1,1547,11.549451,982
17,2015-06-01,475,17699,480,EAST0102,127.003851,37.261052,1,1400,12.642143,925
18,2015-06-01,446,21300,467,EAST0103,195.666286,47.757847,1,1519,14.022383,1073
19,2015-06-01,772,18522,466,EAST0109,97.231429,23.992227,1,3443,5.379611,2671
20,2015-06-01,123,23921,464,WEST0101,684.667059,194.479674,1,1281,18.673692,1158
21,2015-06-01,589,19802,429,EAST0108,134.594044,33.619694,1,2820,7.021986,2231
22,2015-05-31,482,1421,203,EAST0110,5.320380,2.948132,31,2989,0.475410,2507
23,2015-05-29,527,2393,198,WEST0111,16.097714,4.540796,29,3710,0.645013,3183
24,2015-05-29,595,1969,191,EAST0110,5.765895,3.309243,29,2989,0.658749,2394
25,2015-06-02,803,4645,191,WEST0111,13.646932,5.784557,2,3710,1.252022,2907
26,2015-06-02,798,3936,189,EAST0110,6.685032,4.932330,2,2989,1.316828,2191
27,2015-06-03,769,3499,181,EAST0110,6.285195,4.550065,3,2989,1.170626,2220
28,2015-06-04,783,3593,181,EAST0110,10.775284,4.588761,4,2989,1.202074,2206
29,2015-05-31,439,1486,176,WEST0111,6.955102,3.384965,31,3710,0.400539,3271
...,...,...,...,...,...,...,...,...,...,...,...
124,2015-05-31,83,1631,102,WEST0101,41.373245,19.650602,31,1281,1.273224,1198
125,2015-06-04,270,3096,100,EAST0101,26.057856,11.466666,4,1562,1.982074,1292
126,2015-05-30,302,2096,100,EAST0103,10.510311,6.940397,30,1519,1.379855,1217
127,2015-05-30,92,2494,100,WEST0101,50.208577,27.108695,30,1281,1.946916,1189
128,2015-05-29,269,2051,100,WEST0106,28.449595,7.624535,29,1547,1.325792,1278
129,2015-05-30,364,2708,99,WEST0104,22.542126,7.439560,30,1547,1.750485,1183
130,2015-05-30,492,2521,98,WEST0109,18.720095,5.123983,30,3273,0.770241,2781
131,2015-06-04,456,2655,97,EAST0108,13.868794,5.822368,4,2820,0.941489,2364
132,2015-06-03,424,3541,95,EAST0105,27.951552,8.351415,3,1874,1.889541,1450
133,2015-06-02,125,3833,95,WEST0107,92.059280,30.664000,2,1580,2.425949,1455
134,2015-06-03,294,3382,92,EAST0106,26.413090,11.503401,3,2301,1.469796,2007
135,2015-05-31,366,2053,92,WEST0103,22.718468,5.609289,31,1483,1.384356,1117
136,2015-05-29,243,1875,91,WEST0108,37.656090,7.716049,29,2626,0.714014,2383
137,2015-05-29,217,1711,88,EAST0106,19.113308,7.884792,29,2301,0.743590,2084
138,2015-06-04,528,2700,87,EAST0107,8.952228,5.113636,4,3188,0.846926,2660
139,2015-06-04,277,3098,86,EAST0106,22.804744,11.184115,4,2301,1.346371,2024
140,2015-06-04,415,3299,85,EAST0105,27.454231,7.949397,4,1874,1.760406,1459
141,2015-05-30,216,2084,83,EAST0101,21.461125,9.648148,30,1562,1.334187,1346
142,2015-05-30,290,2591,80,WEST0106,34.172269,8.934482,30,1547,1.674855,1257
143,2015-05-30,361,1784,79,EAST0108,8.295742,4.941828,30,2820,0.632624,2459
144,2015-06-04,796,4420,78,EAST0109,17.067586,5.552763,4,3443,1.283764,2647
145,2015-05-31,78,982,78,WEST0107,22.118235,12.589743,31,1580,0.621519,1502
146,2015-06-03,118,3431,78,WEST0107,77.357869,29.076271,3,1580,2.171519,1462
147,2015-06-04,121,3040,73,WEST0107,69.821327,25.123966,4,1580,1.924051,1459
148,2015-05-29,86,1897,70,WEST0107,48.904595,22.058139,29,1580,1.200633,1494
149,2015-05-30,228,2047,69,EAST0106,19.475681,8.978070,30,2301,0.889613,2073
150,2015-05-30,414,1740,69,EAST0107,6.931507,4.202898,30,3188,0.545797,2774
151,2015-05-30,326,1882,68,EAST0105,15.145025,5.773006,30,1874,1.004269,1548
152,2015-05-30,250,2061,67,WEST0108,39.937858,8.244000,30,2626,0.784844,2376
153,2015-05-30,91,2214,49,WEST0107,57.385348,24.329670,30,1580,1.401266,1489

In [4]:
dframe.describe()

,CountStudiosWTrans,TotalTrans,Duration,StdDevNumTrans,TransPerStudioWTrans,DayOfMonthNumber,TotalCountStudios,TransPerTotalStudioCount,StudiosWNoTrans
count,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000
mean,432.746753,5684.506494,187.675325,49.334524,15.388649,14.285714,2303.136364,2.798018,1870.389610
std,197.832786,7501.878323,155.893037,126.907326,29.105005,13.690183,848.303637,4.008037,738.316866
min,77.000000,982.000000,49.000000,4.439701,2.948132,1.000000,1281.000000,0.324588,915.000000
25%,306.500000,2033.000000,108.250000,10.576555,5.210165,2.000000,1547.000000,0.891317,1204.000000
50%,414.500000,3134.000000,134.000000,16.560222,7.362248,4.000000,1883.500000,1.382106,1492.000000
75%,532.500000,3874.750000,163.000000,43.635379,12.112407,30.000000,3188.000000,2.215915,2599.500000
max,991.000000,39619.000000,786.000000,1332.724143,279.007042,31.000000,3710.000000,25.075316,3292.000000

In [5]:
dframe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 154 entries, 0 to 153
Data columns (total 11 columns):
rundate                     154 non-null datetime64[ns]
CountStudiosWTrans          154 non-null int64
TotalTrans                  154 non-null int64
Duration                    154 non-null int64
JobPartition                154 non-null object
StdDevNumTrans              154 non-null float64
TransPerStudioWTrans        154 non-null float64
DayOfMonthNumber            154 non-null int64
TotalCountStudios           154 non-null int64
TransPerTotalStudioCount    154 non-null float64
StudiosWNoTrans             154 non-null int64
dtypes: datetime64[ns](1), float64(3), int64(6), object(1)
memory usage: 14.4+ KB